button_mapping:
  controller:
    ABS_RZ:
      input: ''
    ABS_Z:
      input: ''

    ABS_X:
      input: h
      stick: left
    ABS_Y:
      input: v
      invert: True
      stick: left
    BTN_THUMBL:
      input: l_stick

    ABS_RX:
      input: h
      stick: right
    ABS_RY:
      input: v
      invert: True
      stick: right
    BTN_THUMBR:
      input: r_stick

    ABS_HAT0Y:
      input: down
      digital: 
        1: down
        -1: up
    ABS_HAT0X:
      input: right
      digital:
        1: right
        -1: left

    BTN_NORTH:
      input: y
    BTN_EAST:
      input: a
    BTN_SOUTH:
      input: b
    BTN_WEST:
      input: x

    BTN_MODE:
      input: home
    BTN_START:
      input: plus
    BTN_SELECT:
      input: minus

    BTN_TL:
      input: l
    BTN_TL2:
      input: zl
    BTN_TR:
      input: r
    BTN_TR2:
      input: zr
reconnect_bt_addr:
